security:
  providers:
    user_db:
      entity: { class: App\Entity\Accounts, property: name }

  role_hierarchy:
    ROLE_USER:        [ROLE_READ_ONLY]
    ROLE_ADMIN:       [ROLE_USER]
    ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false

    main:
      pattern: ^/
      guard:
        authenticators:
          - App\Security\LoginFormAuthenticator

      logout:
        path:   logoutPage
      anonymous:    true

  access_control:
    - { path: ^/, role: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: '%env(SECURE_SCHEME)%' }
    - { path: ^/donate, role: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: '%env(SECURE_SCHEME)%'  }
    - { path: ^/login, role: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: '%env(SECURE_SCHEME)%' }
    - { path: ^/user, role: ROLE_USER, requires_channel: '%env(SECURE_SCHEME)%' }
    - { path: ^/admin, role: ROLE_ADMIN, requires_channel: '%env(SECURE_SCHEME)%' }